@extends('layouts.master')
@section('body_class', 'is-dpm')
@php
    $instructorName = data_get($contact, 'name') ?: 'Đinh Tuấn Anh';
    $instructorAvatar = data_get($contact, 'avatar');
    if ($instructorAvatar && !\Illuminate\Support\Str::startsWith($instructorAvatar, ['http://', 'https://', '//', '/'])) {
        $instructorAvatar = asset($instructorAvatar);
    }
    $pageDescription = $course->seo_description ?: $course->short_description;
    $temporaryImage = asset('site/assets/img/courses/digital-performance-workspace.png');
@endphp
@section('page_title', $course->seo_title ?: $course->title . ' | ' . $instructorName)
@section('meta_description', $pageDescription)
@section('og_title', $course->title)
@section('og_description', $pageDescription)
@section('og_image', $temporaryImage)
@push('head')
<link rel="stylesheet" href="{{ asset('site/assets/css/digital-performance.css') }}?v={{ filemtime(public_path('site/assets/css/digital-performance.css')) }}">
@endpush
@push('structured_data')
@include('partials.jsonld-course', ['course' => $course])
@endpush
@section('content')
<div class="dpm-page">
@if(!empty($isPreview))<div class="dpm-preview" role="status">Bản xem trước — khóa học chưa mở</div>@endif
<section class="dpm-hero" aria-labelledby="dpm-title"><div class="dpm-wrap dpm-hero-grid"><div>
 <p class="dpm-eyebrow"><span></span> ĐINH TUẤN ANH / KHÓA HỌC DATA ANALYTICS</p>
 <h1 id="dpm-title">{{ $course->title }}</h1>
 <p class="dpm-hero-message">Hiểu dữ liệu.<br><em>Tìm insight.</em><br>Ra quyết định tốt hơn.</p>
 <p class="dpm-lead">{{ $course->short_description }}</p>
 <div class="dpm-actions"><a class="dpm-button" href="#dang-ky">Đăng ký tư vấn <span aria-hidden="true">↗</span></a><a class="dpm-text-link" href="#lo-trinh">Khám phá lộ trình ↓</a></div>
 <p class="dpm-hero-note">Video bài giảng · Thực hành dự án · Nhóm hỏi đáp, chữa bài</p>
</div><div class="dpm-hero-media"><figure class="dpm-hero-visual"><img src="{{ $temporaryImage }}" width="1536" height="1024" fetchpriority="high" alt="Không gian làm việc với laptop hiển thị dữ liệu và biểu đồ phân tích"><figcaption><span>ĐỌC DỮ LIỆU · TÌM INSIGHT · RA QUYẾT ĐỊNH</span></figcaption></figure><div class="dpm-hero-facts" aria-label="Hình thức khóa học"><div><strong>05 buổi</strong><span>Lộ trình học</span></div><div><strong>Video</strong><span>Học theo từng bài</span></div><div><strong>Chữa bài</strong><span>Trao đổi trong nhóm</span></div></div></div></div></section>
<nav class="dpm-subnav" aria-label="Nội dung khóa học"><div class="dpm-wrap"><a href="#tong-quan">Tổng quan</a><a href="#lo-trinh">Lộ trình</a><a href="#cach-hoc">Cách học</a><a href="#giang-vien">Giảng viên</a><a href="#hoc-phi">Học phí</a><a href="#dang-ky">Đăng ký ↗</a></div></nav>
<section class="dpm-section" id="tong-quan"><div class="dpm-wrap"><div class="dpm-section-head"><div><p class="dpm-eyebrow">01 / TƯ DUY DỮ LIỆU CHO CÔNG VIỆC</p><h2>Những ai nên tham gia<br>khóa học này?</h2></div><p>Dành cho bất kỳ ai muốn làm việc hiệu quả hơn với dữ liệu, không chỉ những người làm Data chuyên sâu.</p></div><div class="dpm-four"><article class="dpm-audience"><span class="dpm-number">01</span><h3>Marketer</h3><p>Đọc hiểu số liệu, đánh giá hiệu quả chiến dịch và đưa ra quyết định dựa trên dữ liệu.</p></article><article class="dpm-audience"><span class="dpm-number">02</span><h3>Founder / Business Owner</h3><p>Đọc dữ liệu kinh doanh, nhận diện vấn đề và tìm ra cơ hội tăng trưởng.</p></article><article class="dpm-audience"><span class="dpm-number">03</span><h3>Analyst / Product Manager</h3><p>Phân tích, trực quan hóa dữ liệu và truyền tải insight rõ ràng để hỗ trợ ra quyết định.</p></article><article class="dpm-audience"><span class="dpm-number">04</span><h3>Student / Career Starter</h3><p>Xây nền tảng tư duy dữ liệu và kỹ năng thực hành có thể ứng dụng ngay trong học tập, công việc.</p></article></div></div></section>
<section class="dpm-section dpm-outcomes"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">DATA LÀ LỢI THẾ TRONG CÔNG VIỆC</p><h2>Không chỉ là những con số trên màn hình.</h2><p class="dpm-muted">Biến dữ liệu thành insight rõ ràng, có ngữ cảnh và có thể hành động.</p></div><div><ul class="dpm-benefits"><li>Xây dựng tư duy phân tích dữ liệu bài bản</li><li>Làm sạch, xử lý và phân tích dữ liệu thực tế</li><li>Tìm insight thay vì chỉ đọc số</li><li>Trực quan hóa dữ liệu rõ ràng</li><li>Xây dựng dashboard phục vụ quyết định</li><li>Trình bày insight thành câu chuyện có sức thuyết phục</li></ul></div></div></section>
<section class="dpm-section" id="lo-trinh"><div class="dpm-wrap"><div class="dpm-section-head"><div><p class="dpm-eyebrow">02 / NỘI DUNG KHÓA HỌC</p><h2>05 buổi học.<br>Từ dữ liệu đến quyết định.</h2></div><p>Từ câu hỏi đúng, dữ liệu sạch và phân tích sâu đến dashboard, storytelling và recommendation.</p></div><div class="dpm-curriculum">@foreach(config('data-analysis.modules', []) as $module)<details @if($loop->first) open @endif><summary><span class="dpm-module-number">Buổi {{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><span class="dpm-module-title">{{ $module[0] }}</span><span class="dpm-expand" aria-hidden="true"></span></summary><p>{{ $module[1] }}</p></details>@endforeach</div>@if($course->content)<div class="dpm-extra">{!! $course->content !!}</div>@endif<div class="dpm-curriculum-footer"><p>Template phân tích dữ liệu · Framework tìm insight · Dashboard examples · Nhóm hỏi đáp và chữa bài.</p><a class="dpm-text-link" href="#dang-ky">Nhận tư vấn lộ trình ↗</a></div></div></section>
<section class="dpm-section dpm-learning" id="cach-hoc"><div class="dpm-wrap"><p class="dpm-eyebrow">03 / HỌC THEO LỘ TRÌNH</p><h2>Học qua video.<br>Thực hành. Chữa bài.</h2><div class="dpm-three"><article><span class="dpm-number">01 — XEM &amp; HIỂU</span><h3>Video bài giảng theo lộ trình</h3><p>Nắm tư duy và cách làm qua từng buổi học.</p></article><article><span class="dpm-number">02 — LÀM &amp; KIỂM CHỨNG</span><h3>Thực hành trên dữ liệu thực tế</h3><p>Áp dụng kiến thức vào tình huống và dữ liệu cụ thể.</p></article><article><span class="dpm-number">03 — HỎI &amp; CẢI THIỆN</span><h3>Feedback và tối ưu bài làm</h3><p>Nhận góp ý để diễn giải và trình bày insight rõ ràng hơn.</p></article></div></div></section>
<section class="dpm-section"><div class="dpm-wrap"><div class="dpm-section-head"><div><p class="dpm-eyebrow">CASE STUDY</p><h2>Biến dữ liệu thành insight<br>có giá trị.</h2></div><p>Thực hành đọc dữ liệu đúng ngữ cảnh, tìm điểm đáng chú ý và chuyển thành đề xuất có thể hành động.</p></div><div class="dpm-four"><article class="dpm-audience"><span class="dpm-number">01</span><h3>Marketing performance analysis</h3><p>Đánh giá hiệu quả để xác định điểm cần tối ưu.</p></article><article class="dpm-audience"><span class="dpm-number">02</span><h3>Customer behavior analysis</h3><p>Hiểu hành vi để phát hiện cơ hội và vấn đề.</p></article><article class="dpm-audience"><span class="dpm-number">03</span><h3>Business dashboard</h3><p>Tổ chức chỉ số thành một góc nhìn dễ theo dõi.</p></article><article class="dpm-audience"><span class="dpm-number">04</span><h3>Data storytelling</h3><p>Trình bày insight thành câu chuyện thuyết phục.</p></article></div><figure class="dpm-visual"><img src="{{ $temporaryImage }}" width="1536" height="1024" loading="lazy" alt="Minh họa không gian phân tích dữ liệu và dashboard"><figcaption class="dpm-asset-note">Ảnh minh họa tạm thời — sẽ được thay bằng case study thực tế.</figcaption></figure></div></section>
<section class="dpm-section" id="giang-vien"><div class="dpm-wrap dpm-instructor"><div class="dpm-instructor-profile"><div class="dpm-portrait">@if($instructorAvatar)<img src="{{ $instructorAvatar }}" alt="{{ $instructorName }}" loading="lazy" width="600" height="700">@else<div class="dpm-monogram" aria-hidden="true">TA<span>Đinh Tuấn Anh</span></div>@endif<span>GIẢNG VIÊN ĐỒNG HÀNH</span></div>@if(data_get($contact, 'description'))<p class="dpm-profile-summary">{{ data_get($contact, 'description') }}</p>@endif</div><div><p class="dpm-eyebrow">04 / HỌC CÙNG</p><h2>{{ $instructorName }}</h2><p class="dpm-instructor-intro">Data Analytics &amp; Digital Growth Instructor.</p>@if(data_get($contact, 'about_me'))<div class="dpm-bio">{!! data_get($contact, 'about_me') !!}</div>@endif<div class="dpm-instructor-note">Trao đổi câu hỏi, bài thực hành và cách trình bày insight trong nhóm học tập.</div><a class="dpm-text-link" href="{{ route('about') }}">Tìm hiểu thêm về giảng viên ↗</a></div></div></section>
<section class="dpm-section dpm-enroll" id="hoc-phi"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">05 / ĐẦU TƯ CHO KIẾN THỨC</p><h2>Đăng ký khóa học<br>Data Analysis &amp; Visualization.</h2><p class="dpm-price">{{ number_format($course->sale_price ?? $course->price ?? 3000000, 0, ',', '.') }} <span>VNĐ</span></p><p class="dpm-price-label">Học phí khóa học</p><ul class="dpm-benefits"><li>Lộ trình từ nền tảng đến thực hành</li><li>Video bài giảng</li><li>Template phân tích dữ liệu</li><li>Framework tìm insight</li><li>Dashboard examples</li><li>Nhóm hỏi đáp chữa bài</li></ul></div><div class="dpm-form-card" id="dang-ky"><p class="dpm-eyebrow">TRAO ĐỔI VỀ KHÓA HỌC</p><h3>Đăng ký tư vấn</h3><p>Để lại thông tin để được tư vấn nội dung, cách học và hướng dẫn đăng ký.</p>@if(session('success'))<div class="dpm-success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="dpm-error" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<form action="{{ route('lead.store') }}" method="POST" data-submit-label="Đang gửi...">@csrf<input type="hidden" name="source_page" value="data_analysis_landing"><input type="hidden" name="course_id" value="{{ $course->id }}"><label for="data-name">Họ và tên <span>*</span></label><input id="data-name" name="name" value="{{ old('name') }}" required maxlength="255" autocomplete="name" placeholder="Tên của bạn"><label for="data-phone">Số điện thoại <span>*</span></label><input id="data-phone" type="tel" name="phone" value="{{ old('phone') }}" required maxlength="30" autocomplete="tel" placeholder="Số điện thoại liên hệ"><label for="data-email">Email <small>(không bắt buộc)</small></label><input id="data-email" type="email" name="email" value="{{ old('email') }}" maxlength="255" autocomplete="email" placeholder="Email của bạn"><label for="data-message">Bạn muốn học để làm gì?</label><textarea id="data-message" name="message" rows="3" placeholder="Chia sẻ mục tiêu hoặc điều bạn muốn hỏi...">{{ old('message') }}</textarea><div class="dpm-honeypot" aria-hidden="true"><label for="data-website">Website</label><input id="data-website" name="website" tabindex="-1" autocomplete="off"></div><button class="dpm-button" type="submit">Gửi đăng ký tư vấn <span aria-hidden="true">↗</span></button><p class="dpm-small">Thông tin được sử dụng để liên hệ tư vấn khóa học cho bạn.</p></form></div></div></section>
<section class="dpm-section dpm-faq"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">GIẢI ĐÁP TRƯỚC KHI HỌC</p><h2>Câu hỏi thường gặp</h2></div><div><details><summary>Tôi không học Data chuyên sâu có học được không?</summary><p>Có. Khóa học bắt đầu từ tư duy phân tích và cách đặt câu hỏi phù hợp với công việc.</p></details><details><summary>Có cần biết Excel hoặc Power BI trước không?</summary><p>Không bắt buộc. Bạn sẽ được tư vấn mức độ phù hợp và cách chuẩn bị trước khi đăng ký.</p></details><details><summary>Có thực hành trên dữ liệu thật không?</summary><p>Có. Bài học có phần thực hành trên dữ liệu và tình huống gần với công việc thực tế.</p></details><details><summary>Có áp dụng cho Marketing và Business không?</summary><p>Có. Các ví dụ bao gồm phân tích hiệu quả Marketing, hành vi khách hàng và dashboard kinh doanh.</p></details></div></div></section>
<div class="dpm-closing"><div class="dpm-wrap"><span>Hiểu dữ liệu. Kể câu chuyện. Ra quyết định tốt hơn.</span><a href="#dang-ky">Bắt đầu cùng Tuấn Anh ↗</a></div></div>
</div>
@endsection
