@extends('layouts.master')
@section('body_class', 'is-dpm')
@php
    $instructorName = data_get($contact, 'name') ?: 'Đinh Tuấn Anh';
    $instructorAvatar = data_get($contact, 'avatar');
    if ($instructorAvatar && !\Illuminate\Support\Str::startsWith($instructorAvatar, ['http://', 'https://', '//', '/'])) {
        $instructorAvatar = asset($instructorAvatar);
    }
    $pageDescription = $course->seo_description ?: $course->short_description;
@endphp
@section('page_title', $course->seo_title ?: $course->title . ' | ' . $instructorName)
@section('meta_description', $pageDescription)
@section('og_title', $course->title)
@section('og_description', $pageDescription)
@section('og_image', asset('site/assets/img/courses/facebook-community-hero.webp'))
@push('head')
<link rel="stylesheet" href="{{ asset('site/assets/css/digital-performance.css') }}?v={{ filemtime(public_path('site/assets/css/digital-performance.css')) }}">
@endpush
@push('structured_data')
@include('partials.jsonld-course', ['course' => $course])
@endpush
@section('content')
<div class="dpm-page">
@if(!empty($isPreview))<div class="dpm-preview" role="status">Bản xem trước — khóa học chưa mở</div>@endif
<section class="dpm-hero" aria-labelledby="dpm-title"><div class="dpm-wrap dpm-hero-grid"><div>
 <p class="dpm-eyebrow"><span></span> ĐINH TUẤN ANH / KHÓA HỌC COMMUNITY GROWTH</p>
 <h1 id="dpm-title">{{ $course->title }}</h1>
 <p class="dpm-hero-message">Xây cộng đồng.<br><em>Tạo traffic.</em></p>
 <p class="dpm-lead">{{ $course->short_description }}</p>
 <div class="dpm-actions"><a class="dpm-button" href="#dang-ky">Đăng ký tư vấn <span aria-hidden="true">↗</span></a><a class="dpm-text-link" href="#lo-trinh">Khám phá lộ trình ↓</a></div>
 <p class="dpm-hero-note">Video bài giảng · Thực hành xây Community · Nhóm hỏi đáp &amp; chữa bài</p>
</div><div class="dpm-hero-media"><figure class="dpm-hero-visual"><img src="{{ asset('site/assets/img/courses/facebook-community-hero.webp') }}" width="1536" height="1024" fetchpriority="high" alt="Không gian làm việc quản trị cộng đồng với laptop hiển thị dữ liệu tăng trưởng thành viên"><figcaption><span>XÂY CỘNG ĐỒNG · TẠO TRAFFIC · TẠO GIÁ TRỊ</span></figcaption></figure><div class="dpm-hero-facts" aria-label="Hình thức khóa học"><div><strong>05 buổi</strong><span>Lộ trình học</span></div><div><strong>Video</strong><span>Học theo từng bài</span></div><div><strong>Chữa bài</strong><span>Trao đổi trong nhóm</span></div></div></div></div></section>
<nav class="dpm-subnav" aria-label="Nội dung khóa học"><div class="dpm-wrap"><a href="#tong-quan">Tổng quan</a><a href="#lo-trinh">Lộ trình</a><a href="#cach-hoc">Cách học</a><a href="#giang-vien">Giảng viên</a><a href="#hoc-phi">Học phí</a><a href="#dang-ky">Đăng ký ↗</a></div></nav>
<section class="dpm-section" id="tong-quan"><div class="dpm-wrap"><div class="dpm-section-head"><div><p class="dpm-eyebrow">01 / BẮT ĐẦU VỚI TÀI SẢN SỞ HỮU</p><h2>Những ai nên tham gia<br>khóa học này?</h2></div><p>Dành cho người muốn xây dựng Community thành một kênh Marketing bền vững, không chỉ là nơi đăng bài.</p></div><div class="dpm-four"><article class="dpm-audience"><span class="dpm-number">01</span><h3>Marketer</h3><p>Build owned media. Không phụ thuộc hoàn toàn vào quảng cáo.</p></article><article class="dpm-audience"><span class="dpm-number">02</span><h3>Founder</h3><p>Xây cộng đồng quanh thương hiệu.</p></article><article class="dpm-audience"><span class="dpm-number">03</span><h3>Agency / Freelancer</h3><p>Thêm dịch vụ Community Growth.</p></article><article class="dpm-audience"><span class="dpm-number">04</span><h3>Content Creator</h3><p>Biến follower thành community.</p></article></div></div></section>
<section class="dpm-section dpm-outcomes"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">COMMUNITY LÀ TÀI SẢN MARKETING</p><h2>Facebook Group không chỉ là nơi đăng bài.</h2><p class="dpm-muted">Một Community tốt tạo owned audience, nuôi dưỡng customer relationship, mở rộng traffic source và trở thành sales channel.</p></div><div><ul class="dpm-benefits"><li>Owned audience</li><li>Customer relationship</li><li>Traffic source</li><li>Sales channel</li></ul></div></div><div class="dpm-wrap"><figure class="dpm-visual"><img src="{{ asset('site/assets/img/courses/community-ecosystem.webp') }}" width="1536" height="1024" loading="lazy" alt="Sơ đồ Community kết nối Profile, Page, Messenger, Website và CRM"><figcaption class="dpm-asset-note">Community kết nối Profile · Page · Messenger · Website · CRM</figcaption></figure></div></section>
<section class="dpm-section"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">HỌC ĐỂ XÂY DỰNG</p><h2>Community thực chiến.</h2><p class="dpm-muted">Từ research niche và cấu trúc Group đến tăng trưởng, vận hành và doanh thu.</p></div><div class="dpm-outcome-list"><article><span>↗</span><div><h3>Build</h3><p>Research niche. Setup Group. Create structure.</p></div></article><article><span>↗</span><div><h3>Grow</h3><p>Member acquisition. Traffic system. Content distribution.</p></div></article><article><span>↗</span><div><h3>Operate</h3><p>Moderation. Automation. Community management.</p></div></article><article><span>↗</span><div><h3>Monetize</h3><p>Lead generation. Sales funnel. Revenue.</p></div></article></div></div></section>
<section class="dpm-section" id="lo-trinh"><div class="dpm-wrap"><div class="dpm-section-head"><div><p class="dpm-eyebrow">02 / NỘI DUNG KHÓA HỌC</p><h2>05 buổi học.<br>Từ tư duy đến thực hành.</h2></div><p>Xây Group → thu hút thành viên → vận hành → đo lường → mở rộng hệ thống Community.</p></div><div class="dpm-curriculum">@foreach(config('facebook-community.modules', []) as $module)<details @if($loop->first) open @endif><summary><span class="dpm-module-number">Buổi {{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><h3>{{ $module[0] }}</h3><span class="dpm-expand" aria-hidden="true"></span></summary><p>{{ $module[1] }}</p></details>@endforeach</div>@if($course->content)<div class="dpm-extra">{!! $course->content !!}</div>@endif<div class="dpm-curriculum-footer"><p>Template xây Group · Framework tăng trưởng · Tool stack · Nhóm hỏi đáp và chữa bài.</p><a class="dpm-text-link" href="#dang-ky">Nhận tư vấn lộ trình ↗</a></div></div></section>
<section class="dpm-section dpm-learning" id="cach-hoc"><div class="dpm-wrap"><p class="dpm-eyebrow">03 / HỌC THEO LỘ TRÌNH</p><h2>Học qua video.<br>Thực hành. Chữa bài.</h2><div class="dpm-three"><article><span class="dpm-number">01 — XEM &amp; HIỂU</span><h3>Video bài giảng theo lộ trình</h3><p>Nắm nền tảng và cách triển khai từng bước.</p></article><article><span class="dpm-number">02 — LÀM &amp; KIỂM CHỨNG</span><h3>Áp dụng xây Community thật</h3><p>Thực hành trên Community và hệ thống của bạn.</p></article><article><span class="dpm-number">03 — HỎI &amp; CẢI THIỆN</span><h3>Nhận feedback trực tiếp</h3><p>Trao đổi, nhận góp ý và điều chỉnh cách làm.</p></article></div></div></section>
<section class="dpm-section"><div class="dpm-wrap"><div class="dpm-section-head"><div><p class="dpm-eyebrow">CASE STUDY</p><h2>Xây dựng Community<br>500K+ thành viên.</h2></div><p>Hội thích mặc linen: một Community phát triển thành điểm chạm nội dung, tương tác và traffic dài hạn.</p></div><div class="dpm-three"><article class="dpm-audience"><span class="dpm-number">500K+</span><h3>Members</h3></article><article class="dpm-audience"><span class="dpm-number">24K+</span><h3>Posts &amp; comments</h3><p>Trong 28 ngày</p></article><article class="dpm-audience"><span class="dpm-number">3M+</span><h3>Views</h3></article></div><div class="dpm-case-grid"><figure><img src="{{ asset('site/assets/img/courses/community-case-growth.png') }}" loading="lazy" width="1536" height="1024" alt="Minh họa dashboard tăng trưởng Community"><figcaption>Minh họa tăng trưởng Community</figcaption></figure><figure><img src="{{ asset('site/assets/img/courses/community-case-engagement.png') }}" loading="lazy" width="1536" height="1024" alt="Minh họa dashboard tương tác Community"><figcaption>Minh họa hoạt động và tương tác</figcaption></figure></div></div></section>
<section class="dpm-section" id="giang-vien"><div class="dpm-wrap dpm-instructor"><div class="dpm-instructor-profile"><div class="dpm-portrait">@if($instructorAvatar)<img src="{{ $instructorAvatar }}" alt="{{ $instructorName }}" loading="lazy" width="600" height="700">@else<div class="dpm-monogram" aria-hidden="true">TA<span>Đinh Tuấn Anh</span></div>@endif<span>GIẢNG VIÊN ĐỒNG HÀNH</span></div>@if(data_get($contact, 'description'))<p class="dpm-profile-summary">{{ data_get($contact, 'description') }}</p>@endif</div><div><p class="dpm-eyebrow">04 / HỌC CÙNG</p><h2>{{ $instructorName }}</h2><p class="dpm-instructor-intro">Community Growth Strategist.</p><div class="dpm-instructor-note">Kinh nghiệm xây Community lớn, Content ecosystem, Community operation và Digital growth.</div><a class="dpm-text-link" href="{{ route('about') }}">Tìm hiểu thêm về giảng viên ↗</a></div></div></section>
<section class="dpm-section dpm-enroll" id="hoc-phi"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">05 / ĐẦU TƯ CHO KIẾN THỨC</p><h2>Đăng ký khóa học<br>Facebook Community Growth.</h2><p class="dpm-price">{{ number_format($course->sale_price ?? $course->price ?? 3000000, 0, ',', '.') }} <span>VNĐ</span></p><p class="dpm-price-label">Học phí khóa học</p><ul class="dpm-benefits"><li>Lộ trình từ nền tảng đến thực chiến</li><li>Video bài giảng</li><li>Template xây Group</li><li>Framework tăng trưởng</li><li>Tool stack</li><li>Nhóm hỏi đáp chữa bài</li></ul></div><div class="dpm-form-card" id="dang-ky"><p class="dpm-eyebrow">TRAO ĐỔI VỀ KHÓA HỌC</p><h3>Đăng ký tư vấn</h3><p>Để lại thông tin để được tư vấn nội dung, cách học và hướng dẫn đăng ký.</p>@if(session('success'))<div class="dpm-success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="dpm-error" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<form action="{{ route('lead.store') }}" method="POST" data-submit-label="Đang gửi...">@csrf<input type="hidden" name="source_page" value="facebook_community_landing"><input type="hidden" name="course_id" value="{{ $course->id }}"><label for="community-name">Họ và tên <span>*</span></label><input id="community-name" name="name" value="{{ old('name') }}" required maxlength="255" autocomplete="name" placeholder="Tên của bạn"><label for="community-phone">Số điện thoại <span>*</span></label><input id="community-phone" type="tel" name="phone" value="{{ old('phone') }}" required maxlength="30" autocomplete="tel" placeholder="Số điện thoại liên hệ"><label for="community-email">Email <small>(không bắt buộc)</small></label><input id="community-email" type="email" name="email" value="{{ old('email') }}" maxlength="255" autocomplete="email" placeholder="Email của bạn"><label for="community-message">Bạn muốn học để làm gì?</label><textarea id="community-message" name="message" rows="3" placeholder="Chia sẻ mục tiêu hoặc điều bạn muốn hỏi...">{{ old('message') }}</textarea><div class="dpm-honeypot" aria-hidden="true"><label for="community-website">Website</label><input id="community-website" name="website" tabindex="-1" autocomplete="off"></div><button class="dpm-button" type="submit">Gửi đăng ký tư vấn <span aria-hidden="true">↗</span></button><p class="dpm-small">Thông tin được sử dụng để liên hệ tư vấn khóa học cho bạn.</p></form></div></div></section>
<section class="dpm-section dpm-faq"><div class="dpm-wrap dpm-two"><div><p class="dpm-eyebrow">GIẢI ĐÁP TRƯỚC KHI HỌC</p><h2>Câu hỏi thường gặp</h2></div><div><details><summary>Tôi chưa có Group có học được không?</summary><p>Có. Khóa học hướng dẫn từ research niche, setup Group đến cấu trúc và hành trình thành viên.</p></details><details><summary>Khóa học có hướng dẫn kéo member không?</summary><p>Có. Bạn sẽ học member acquisition, traffic flow và content distribution để phát triển thành viên phù hợp.</p></details><details><summary>Có dạy tool quản lý Community không?</summary><p>Tool stack và cách dùng automation trong vận hành Community được giới thiệu trong lộ trình học.</p></details><details><summary>Có áp dụng cho bán hàng không?</summary><p>Có. Community được đặt trong hệ thống tạo lead, sales funnel và xây quan hệ khách hàng dài hạn.</p></details></div></div></section>
<div class="dpm-closing"><div class="dpm-wrap"><span>Xây cộng đồng có hệ thống. Phát triển bền vững.</span><a href="#dang-ky">Bắt đầu cùng Tuấn Anh ↗</a></div></div>
</div>
@endsection
